//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TASEntities : DbContext
    {
        public TASEntities()
            : base("name=TASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Designation> Designations { get; set; }
        public virtual DbSet<Education_Qualfication> Education_Qualfication { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Training_Catagory> Training_Catagory { get; set; }
        public virtual DbSet<Training_Intended> Training_Intended { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<Vw_Manage_User> Vw_Manage_User { get; set; }
        public virtual DbSet<Training_Institute> Training_Institute { get; set; }
        public virtual DbSet<Training_Type> Training_Type { get; set; }
        public virtual DbSet<Vw_Training_Type> Vw_Training_Type { get; set; }
        public virtual DbSet<Manage_User> Manage_User { get; set; }
        public virtual DbSet<TAS_Details> TAS_Details { get; set; }
        public virtual DbSet<Vw_Employee_Details> Vw_Employee_Details { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<Vw_Training_Assign> Vw_Training_Assign { get; set; }
        public virtual DbSet<Vw_Feedback> Vw_Feedback { get; set; }
        public virtual DbSet<TrainingDetail> TrainingDetails { get; set; }
        public virtual DbSet<Vw_Admin_Training_Assign> Vw_Admin_Training_Assign { get; set; }
        public virtual DbSet<TraingAssign> TraingAssigns { get; set; }
        public virtual DbSet<Vw_Admin_Training_Assign_Details> Vw_Admin_Training_Assign_Details { get; set; }
        public virtual DbSet<vw_employee_institute> vw_employee_institute { get; set; }
        public virtual DbSet<Vw_Employee_Details_Report> Vw_Employee_Details_Report { get; set; }
        public virtual DbSet<TrainingAssignDetail> TrainingAssignDetails { get; set; }
        public virtual DbSet<Vw_User_Training_Assign> Vw_User_Training_Assign { get; set; }
    }
}
