//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAS_Details
    {
        public int Tas_Id { get; set; }
        public Nullable<int> DesgId { get; set; }
        public Nullable<int> E_Qual_Id { get; set; }
        public Nullable<int> PostId { get; set; }
        public Nullable<int> Traing_Type_Id { get; set; }
        public Nullable<int> Traing_Cata_Id { get; set; }
        public Nullable<int> Tr_Institute_Id { get; set; }
        public Nullable<int> Tr_Intended_Id { get; set; }
        public Nullable<int> Tas_User_Id { get; set; }
        public string Tr_Intended_details { get; set; }
        public string Emp_Name { get; set; }
        public string Present_Post { get; set; }
        public string Edu_Qualification { get; set; }
        public Nullable<System.DateTime> Retirement_Date { get; set; }
        public string Prv_Assignment { get; set; }
        public Nullable<System.DateTime> Tr_Period_From { get; set; }
        public Nullable<System.DateTime> Tr_Period_To { get; set; }
        public string Agreed_For_Training { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
