//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TraingAssign
    {
        public int Tr_AssignID { get; set; }
        public Nullable<int> Tr_Institute_Id { get; set; }
        public Nullable<int> Traing_Type_Id { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> Trfdate { get; set; }
        public Nullable<System.DateTime> Trtdate { get; set; }
        public Nullable<bool> Is_Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModBy { get; set; }
        public Nullable<System.DateTime> Modon { get; set; }
    }
}
