//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingAssignDetail
    {
        public int Tr_Ass_DetailsID { get; set; }
        public Nullable<int> Tr_AssignID { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<bool> IsVisible { get; set; }
        public Nullable<bool> IsEmail { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
