//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingDetail
    {
        public int TraingdeatilsId { get; set; }
        public Nullable<int> Tas_Id { get; set; }
        public Nullable<int> Tr_Institute_Id { get; set; }
        public Nullable<int> Traing_Type_Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Days { get; set; }
        public string Createdby { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> Modby { get; set; }
        public string Modon { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
