//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Admin_Training_Assign
    {
        public Nullable<int> Tr_Institute_Id { get; set; }
        public Nullable<int> Traing_Type_Id { get; set; }
        public int Tr_AssignID { get; set; }
        public string Remarks { get; set; }
        public string Trfdate { get; set; }
        public string Trtdate { get; set; }
        public string Tr_Institute_Name { get; set; }
        public string Traing_Name { get; set; }
    }
}
