//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_employee_institute
    {
        public int Tr_AssignID { get; set; }
        public string FirstName { get; set; }
        public string Emaild { get; set; }
        public string DesgName { get; set; }
    }
}
