//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Employee_Details_Report
    {
        public int Tas_Id { get; set; }
        public string Emp_Name { get; set; }
        public string Retirement_Date { get; set; }
        public string Prv_Assignment { get; set; }
        public string Present_Post { get; set; }
        public string Edu_Qualification { get; set; }
        public Nullable<int> DesgId { get; set; }
        public string DesgName { get; set; }
        public string Tr_Intended_details { get; set; }
        public Nullable<int> Tr_Intended_Id { get; set; }
        public int Tr_Institute_Id { get; set; }
        public int Traing_Type_Id { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Days { get; set; }
        public string Tr_Institute_Name { get; set; }
        public string Traing_Name { get; set; }
        public string Agreed_For_Training { get; set; }
        public string Remarks { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> Crton { get; set; }
    }
}
