//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Feedback
    {
        public int Feedback_Id { get; set; }
        public string From_Date { get; set; }
        public string To_Date { get; set; }
        public string Tr_Relevant { get; set; }
        public string Tr_Length { get; set; }
        public string Tr_Inst_Clear { get; set; }
        public string Trainer_Effective { get; set; }
        public string Tr_Expectation { get; set; }
        public string Tr_Quality { get; set; }
        public string Tr_Daily_Work { get; set; }
        public string Imp_Dev_Process { get; set; }
        public string Explain_Training { get; set; }
        public string CreatedBy { get; set; }
        public string Tr_Institute_Name { get; set; }
        public string Traing_Name { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> Tr_Institute_Id { get; set; }
        public Nullable<int> Traing_Type_Id { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> Crton { get; set; }
    }
}
