//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Training_Type
    {
        public int Traing_Type_Id { get; set; }
        public string Traing_Name { get; set; }
        public string Tr_Address { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> Crton { get; set; }
        public string Tr_Institute_Name { get; set; }
    }
}
