//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DailyReporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_User_Training_Assign
    {
        public int Tr_Ass_DetailsID { get; set; }
        public int Tr_AssignID { get; set; }
        public string Remarks { get; set; }
        public string Trfdate { get; set; }
        public string Trtdate { get; set; }
        public string Emaild { get; set; }
        public Nullable<System.DateTime> Retirement_Date { get; set; }
        public int DesgId { get; set; }
        public string DesgName { get; set; }
        public string Tr_Institute_Name { get; set; }
        public string Traing_Name { get; set; }
        public Nullable<int> Userid { get; set; }
        public string FirstName { get; set; }
        public string CreatedOn { get; set; }
        public Nullable<System.DateTime> Crton { get; set; }
    }
}
